title: 에이치컴퍼니
description: 안드로이드 앱을 만듭니다.
url: "https://hcompany-kr.github.io"
baseurl: ""

timezone: Asia/Seoul

plugins:
  - jekyll-sitemap

permalink: /blog/:categories/:title/

exclude:
  - README.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
